### ISSUE TITLE
initial rake db:migrate throwing errors

### ISSUE THREAD

**Issue by DakotaLMartinez** [learn-co-students/Active-Record-Association-Methods-v-000#40]
running rake db:migrate after cloning this repo is throwing the following error:

==  CreateGenres: migrating ===================================================
-- create_table(:genres)
   -> 0.0175s
==  CreateGenres: migrated (0.0177s) ==========================================

==  AddArtistToSongs: migrating ===============================================
-- add_column(:songs, :artist_id, :integer)
rake aborted!
ActiveRecord::StatementInvalid: SQLite3::SQLException: no such table: songs: ALTER TABLE "songs" ADD "artist_id" integer
/usr/local/rvm/gems/ruby-2.2.1/gems/sqlite3-1.3.10/lib/sqlite3/database.rb:91:in `initialize'
/usr/local/rvm/gems/ruby-2.2.1/gems/sqlite3-1.3.10/lib/sqlite3/database.rb:91:in `new'
/usr/local/rvm/gems/ruby-2.2.1/gems/sqlite3-1.3.10/lib/sqlite3/database.rb:91:in `prepare'
/usr/local/rvm/gems/ruby-2.2.1/gems/sqlite3-1.3.10/lib/sqlite3/database.rb:134:in `execute'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:329:in `block in execute'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract_adapter.rb:473:in `block in log'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract_adapter.rb:467:in `log'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:329:in `execute'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:393:in `add_column'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:453:in `add_column'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.2/lib/active_record/migration.rb:662:in `block in method_missing'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.2/lib/active_record/migration.rb:632:in `block in say_with_time'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.2/lib/active_record/migration.rb:632:in `say_with_time'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.2/lib/active_record/migration.rb:652:in `method_missing'
/home/ubuntu/workspace/orms-and-activerecord/associations/Active-Record-Association-Methods-v-000/db/migrate/04_add_artist_to_songs.rb:3:in `change'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.2/lib/active_record/migration.rb:606:in `exec_migration'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.2/lib/active_record/migration.rb:590:in `block (2 levels) in migrate'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.2/lib/active_record/migration.rb:589:in `block in migrate'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.2/lib/active_record/migration.rb:588:in `migrate'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.2/lib/active_record/migration.rb:421:in `migrate'
/home/ubuntu/workspace/orms-and-activerecord/associations/Active-Record-Association-Methods-v-000/config/environment.rb:25:in `block in migrate_db'
/home/ubuntu/workspace/orms-and-activerecord/associations/Active-Record-Association-Methods-v-000/config/environment.rb:22:in `each'
/home/ubuntu/workspace/orms-and-activerecord/associations/Active-Record-Association-Methods-v-000/config/environment.rb:22:in `migrate_db'
/home/ubuntu/workspace/orms-and-activerecord/associations/Active-Record-Association-Methods-v-000/Rakefile:10:in `block (2 levels) in <top (required)>'
SQLite3::SQLException: no such table: songs
/usr/local/rvm/gems/ruby-2.2.1/gems/sqlite3-1.3.10/lib/sqlite3/database.rb:91:in `initialize'
/usr/local/rvm/gems/ruby-2.2.1/gems/sqlite3-1.3.10/lib/sqlite3/database.rb:91:in `new'
/usr/local/rvm/gems/ruby-2.2.1/gems/sqlite3-1.3.10/lib/sqlite3/database.rb:91:in `prepare'
/usr/local/rvm/gems/ruby-2.2.1/gems/sqlite3-1.3.10/lib/sqlite3/database.rb:134:in `execute'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:329:in `block in execute'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract_adapter.rb:473:in `block in log'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract_adapter.rb:467:in `log'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:329:in `execute'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:393:in `add_column'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:453:in `add_column'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.2/lib/active_record/migration.rb:662:in `block in method_missing'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.2/lib/active_record/migration.rb:632:in `block in say_with_time'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.2/lib/active_record/migration.rb:632:in `say_with_time'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.2/lib/active_record/migration.rb:652:in `method_missing'
/home/ubuntu/workspace/orms-and-activerecord/associations/Active-Record-Association-Methods-v-000/db/migrate/04_add_artist_to_songs.rb:3:in `change'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.2/lib/active_record/migration.rb:606:in `exec_migration'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.2/lib/active_record/migration.rb:590:in `block (2 levels) in migrate'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.2/lib/active_record/migration.rb:589:in `block in migrate'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.2/lib/active_record/migration.rb:588:in `migrate'
/usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.2/lib/active_record/migration.rb:421:in `migrate'
/home/ubuntu/workspace/orms-and-activerecord/associations/Active-Record-Association-Methods-v-000/config/environment.rb:25:in `block in migrate_db'
/home/ubuntu/workspace/orms-and-activerecord/associations/Active-Record-Association-Methods-v-000/config/environment.rb:22:in `each'
/home/ubuntu/workspace/orms-and-activerecord/associations/Active-Record-Association-Methods-v-000/config/environment.rb:22:in `migrate_db'
/home/ubuntu/workspace/orms-and-activerecord/associations/Active-Record-Association-Methods-v-000/Rakefile:10:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

In order to fix the issue, I had to rename the 04_add_artist_to_songs.rb to 06_add_artist_id_to_songs.rb (along with changing the class name in the enclosed file to: class AddArtistIdToSongs) &
I had to rename 05_add_genre_to_songs.rb to 05_add_genre_id_to_songs.rb (along with changing the class name in the enclosed file to: class AddGenreIdToSongs)

After making those changes, running rake:db migrate produced the expected results.

It seems that, for whatever reason, the 4th migration was running before the 1st one that created the songs table, causing an error to be thrown.

**Comment by thegands** [comment]
@DakotaLMartinez I had this issue as well and unfortunately your workaround did not work for me. Are you working in Nitrous? Another student said he got the same error in Nitrous but switched to an OSX virtual machine and got no errors. I am running Linux so i think that's why i'm also getting the error.

The problem is caused by the database migration method inside of config/environment.rb, specifically, i think, the way it reads a directory for files and grabs the filenames. I just copied and pasted a similar looking (but different) method from the [Costume Store Lab](https://github.com/thegands/activerecord-costume-store-todo-v-000/blob/master/Rakefile) and now rake db:migrate works!

if you're interested my pull request is here: https://github.com/learn-co-students/Active-Record-Association-Methods-v-000/pull/67/files

**Comment by mystycs** [comment]
FYI this is still happening i had to change that line 22 on environment.rb to make it work.

**Comment by LonghornRach** [comment]
Just ran this on Learn IDE and also ran into problems. Changing the environment file worked, although I still got warnings after when running db:migrate about "already initialized constants" and "previous definitions"

**Comment by aturkewi** [comment]
Raised the issue on the canonical version of the lab (this -v-000 is just a specific deploy of the lab). It turns out the canonical version has already been fixed and it just needs to be re-deployed. In the process of getting the re-deployed fixed.

Thanks to all here for raising the issue and bringing forward a solution!
